# Generated by Django 2.1.3 on 2018-12-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='text',
            field=models.TextField(default='', verbose_name='Текст песни'),
        ),
        migrations.AddField(
            model_name='songs',
            name='translation',
            field=models.TextField(default='', verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название песни'),
        ),
    ]
