# Generated by Django 2.1.3 on 2018-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20181215_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Ф.И.О.')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('bio', models.TextField(default='', verbose_name='Биография')),
            ],
        ),
    ]
